export const CHANNEL_ID = "C0A0QNJNDGQ";
export const GROUP_ID = "S0A4705UBB3";
export const LOG_CHANNEL_ID = "C0B1U9VLEAJ";
export const WATCHED_CHANNEL_IDS = ["C0A0QNJNDGQ", "C0A7EHZ20JH"] as const;
export const WATCHED_USERGROUP_IDS = [
  "S0AL4S1SGP9",
  "S0AJRA5NBPV",
  "S0A4705UBB3",
] as const;
